### PR TITLE
Upgrade reqwest and pulldown-cmark dependencies

### PR DESCRIPTION
**Pull request by mati865**
About the changes:
- `use_sys_proxy` is now default
- somehow serde stops working with new reqwest unless `derive` feature is enabled
- `codespan` is left with old version because I didn't know how to solve breaking changes

### CODE REVIEW

**Comment by Michael-F-Bryan** [comment]
@mati865 it looks like the travis build failed, any idea what might have caused it?

**Comment by mati865** [comment]
I think Travis has changed their images to not include openssl by default any more.
To confirm that I triggered build for current master branch and it failed the same way: https://travis-ci.com/mati865/mdbook-linkcheck/builds/150833470

You can install `openssl-dev` package on the CI to solve it.

**Comment by palfrey** [comment]
https://github.com/Michael-F-Bryan/mdbook-linkcheck/pull/29 fixes the build issues

**Comment by Michael-F-Bryan** [comment]
@mati865, would you be able to do a `git rebase` and see if CI is happy again?

**Comment by mati865** [comment]
It's green now.

**Pull request merged**
